// <auto-generated />
using System;
using Database_with_LINQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database_with_LINQ.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database_with_LINQ.Models.Class", b =>
                {
                    b.Property<int>("cId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cId"));

                    b.Property<int?>("FacultyfId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fId")
                        .HasColumnType("int");

                    b.HasKey("cId");

                    b.HasIndex("FacultyfId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClasscId")
                        .HasColumnType("int");

                    b.Property<int?>("Studentsid")
                        .HasColumnType("int");

                    b.Property<int>("cId")
                        .HasColumnType("int");

                    b.Property<int>("sId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClasscId");

                    b.HasIndex("Studentsid");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Faculty", b =>
                {
                    b.Property<int>("fId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Standing")
                        .HasColumnType("int");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fId");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Student", b =>
                {
                    b.Property<int>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sid"));

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Class", b =>
                {
                    b.HasOne("Database_with_LINQ.Models.Faculty", null)
                        .WithMany("ClassesTaught")
                        .HasForeignKey("FacultyfId");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Enrollment", b =>
                {
                    b.HasOne("Database_with_LINQ.Models.Class", null)
                        .WithMany("Enrolled")
                        .HasForeignKey("ClasscId");

                    b.HasOne("Database_with_LINQ.Models.Student", null)
                        .WithMany("EnrolledClasses")
                        .HasForeignKey("Studentsid");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Class", b =>
                {
                    b.Navigation("Enrolled");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Faculty", b =>
                {
                    b.Navigation("ClassesTaught");
                });

            modelBuilder.Entity("Database_with_LINQ.Models.Student", b =>
                {
                    b.Navigation("EnrolledClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
